### ISSUE TITLE
In German, some translations are misleading, that is "operational" and "used" are both translated as "In Verwendung"

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-mobility-echarging-dashboard#11]
We should check also the other translations, and make sure that it is clear, what each dashboard box means.

![Selection_117](https://user-images.githubusercontent.com/6096063/80367515-887dd100-888b-11ea-9aeb-544cf0ae06bf.png)
![Selection_115](https://user-images.githubusercontent.com/6096063/80367524-8ca9ee80-888b-11ea-8782-2f7eec61c1e3.png)

**Comment by Piiit** [comment]
@rcavaliere FYI

**Comment by rcavaliere** [comment]
@Piiit the best would be to check correct the translations file and to make a PR, isn't it?

**Comment by Piiit** [comment]
@rcavaliere Si, perfetto...

**Comment by Piiit** [comment]
Fixed, since the new design does not contain these information anymore
