### ISSUE TITLE
As an e-mobility expert, I would like to be sure that the statistics are correct

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-echarging-dashboard#12]
Please provide the queries that the e-mobility web-component (dashboard) is doint towards our API in order to be sure that the views in the dashboard provide the metrics we expect. This information will be included in text in the Green Mobility web site, in which this information is going to be reused

**Comment by Piiit** [comment]
@rcavaliere Hi, I have a collection of queries now, pushed to the repository. However, calculations are then made in javascript.
See https://raw.githubusercontent.com/noi-techpark/webcomp-mobility-echarging-dashboard/development/calls.http for details

**Comment by Piiit** [comment]
@rcavaliere Do you need a `curl` variant of those queries?

**Comment by Piiit** [comment]
@rcavaliere I will now try to reformulate those API calls, that ninja itself creates the final result... for some metrics this is possible, but not for all.

**Comment by rcavaliere** [comment]
@Piiit thanks, I think it is sufficient to understand what results we will present. OK for the riformulation of the API call, this would be something additional, a "nice to have".

**Comment by Piiit** [comment]
@rcavaliere OK, then I add just another enhancement user story for the reformulations... and add some comments how calculations are made.

**Comment by Piiit** [comment]
@rcavaliere Done, see the file mentioned above for details.

**Comment by rcavaliere** [comment]
@Piiit, excellent to have all different queries related to each single KPI! Once we have consolidated the new KPI with STA (see #17), I would suggest to update this with the final API calls description.
The Green Mobility web page is going to be upgraded with a proper legend / description, see draft here:
[200608_Legenda.docx](https://github.com/noi-techpark/webcomp-mobility-echarging-dashboard/files/4754572/200608_Legenda.docx)
In the meantime, let's close this issue
