### ISSUE TITLE
Directly use the API when retrieving calculations/aggregations to have a faster response time

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-mobility-echarging-dashboard#13]
I add some examples to the calls.http file... not all calculations are possible thou

**Comment by Piiit** [comment]
I just did it, because it was part of the testing anyway...

**Comment by Piiit** [comment]
@rcavaliere The new version 1.8.0 has the new calls, be compare the results and response times with the version 1.7.0 for testing... Thx

**Comment by Piiit** [comment]
The new version downloads 18KB from the API, whereas the old version used 103KB :-)

**Comment by rcavaliere** [comment]
I consider this issue closed. When we agree on new KPI with STA, we can improve this web-component and use the documented API calls to explain the presented KPI values.
