### ISSUE TITLE
As an e-mobility expert, I expect to see legends in different languages

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-echarging-dashboard#16]
- [x] DE: Öffentlich, Privat e Privat mit öffentlichem Zugang
- [x] IT: Pubblico, Privato, Privato con accesso pubblico)

@Piit is this configurable or is hard coded in the  e-mobility web-component (dashboard)?

**Comment by Piiit** [comment]
@rcavaliere Done, please test
