### ISSUE TITLE
As an e-mobility expert, I would like that the e-mobility dashboard webcomponent is more compact

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-echarging-dashboard#17]
- [x] view number of charging stations merged with view access to charging stations
- [x] view number of plugs merged with view type of plus

@Piiit can you check if this quite easily implementable by changing the requests to our API by the e-mobility web component (dashboard)?

**UPDATE FROM 2021-02-02**

Todos:
- [x] Reload overlapping 
- [x] Minification?
- [x] 100% not enough in first card: sometimes we check "sactive" and sometimes "smetadata.active", what is the difference here?
- [x] Italian translations @rcavaliere 

Nice to have:
- [x] 4th card for symmetry?
- [x] Move card 3 to 1

**Comment by Piiit** [comment]
@rcavaliere Please ask what we need exactly for this with a simple mockup

**Comment by rcavaliere** [comment]
@Piiit please have a look at this concept. Do you think it is feasible with little effort? I am going to check this STA as well.
![200601_EMobilityDashboardNewConcept](https://user-images.githubusercontent.com/9825179/84075795-0548b280-a9d5-11ea-9ef3-4f3936391f13.jpg)

**Comment by Piiit** [comment]
@rcavaliere I think I can do it directly. In the meantime I move it to backlog. So we can decide for the next sprint if we take it in... ok?

**Comment by rcavaliere** [comment]
@Piiit STA has provided us a feedback that the above mock-up is OK to be implemented. Just a comment, they would like to have the possibility to know the values of each category when you pass over the plot with the mouse (as it is already available in the current view). I move it already in the "Sprint To Do" lane, so that we have it for the next sprint.

**Comment by rcavaliere** [comment]
@Piiit do you think that during this or next sprint you are able to close this user story? STA is starting to ask me about the development timings...

**Comment by Piiit** [comment]
@rcavaliere I will try, but cannot promise for this sprint, but for the next for sure... hope that is ok for you?

**Comment by rcavaliere** [comment]
Would be perfect, I already said to STA in 4 weeks time :-)

**Comment by Piiit** [comment]
@rcavaliere Done, please test under https://webcomponents.opendatahub.testingmachine.eu/webcomponent/f594de36-0136-4c27-a0e6-570fa7014129

**Comment by Piiit** [comment]
@rcavaliere Please check Italian translations... One title is too long and creates distortion inside the first card... We could put a shorter translation, or I would need to change the resizing behavior... thx

**Comment by rcavaliere** [comment]
Don't worry, I will check this, thanks for the work indeed!

**Comment by Piiit** [comment]
@rcavaliere I found a problem... the operational/usage stats are wrong, that is all together are > 100%... In the source code we sometimes check "sactive" and sometimes "smetadata.active"... 

What is the difference here?

**Comment by rcavaliere** [comment]
@Piiit sactive is related to a station, so just consider this! smetadata should be something related to the validity of a metadata record

**Comment by Piiit** [comment]
It seems not to be that simple, we have several "sactive" stations with metadata information, that contradict that information...

Example: Response when I check smetadata.state of only "sactive" stations:

```json
[
    {
      "smetadata.state": "UNAVAILABLE"
    },
    {
      "smetadata.state": "MAINTENANCE"
    },
    {
      "smetadata.state": "AVAILABLE"
    },
    {
      "smetadata.state": "FAULT"
    },
    {
      "smetadata.state": "ACTIVE"
    },
    {
      "smetadata.state": "OCCUPIED"
    },
    {
      "smetadata.state": "TEMPORARYUNAVAILABLE"
    },
    {
      "smetadata.state": "UNKNOWN"
    }
]
```

"sactive" false and true stations give the following result:
```json
[
    {
      "smetadata.state": "UNAVAILABLE"
    },
    {
      "smetadata.state": "MAINTENANCE"
    },
    {
      "smetadata.state": "AVAILABLE"
    },
    {
      "smetadata.state": "FAULT"
    },
    {
      "smetadata.state": "ACTIVE"
    },
    {
      "smetadata.state": "OCCUPIED"
    },
    {
      "smetadata.state": "TEMPORARYUNAVAILABLE"
    },
    {
      "smetadata.state": "UNKNOWN"
    }
  ]
```

**Comment by rcavaliere** [comment]
I think this is related to the matching between EChargingStation / EChargingPlug. Can you provide me some more details so that I can check this?

**Comment by Piiit** [comment]
OK.

**1) smetadata of EChargingPlug contains only outlets:**

Example:
```json
"smetadata": {
        "outlets": [
          {
            "id": "2",
            "maxPower": 11.062,
            "maxCurrent": 16.0,
            "minCurrent": 6.0,
            "outletTypeCode": "Type2Mennekes"
          }
        ]
      }
```

Therefore, this shouldn't be a problem when calculating active/used stations.

**2) EChargingStation has sactive and smetadata.active states**
sactive is a boolean as you know, but does not reflect the content of smetadata.active, which are descriptions of "real" states coming from the data collector. See previous comment...

```http
GET mobility.api.opendatahub.bz.it/v2/flat/EChargingStation?select=smetadata.state&where=sactive.eq.false
```

....gives also ACTIVE stations.

We need to decide now:
1) do we look only at sactive or also smetadata.active (does the data collector work correctly?)
2) if we look at smetadata.active should we consider only sactive == true stations, or also sactive == false?
3) which smetadata.state corresponds to the categories of the web component
- OPERATIONAL_IN_USE
- OPERATIONAL_NOT_IN_USE
- NOT_OPERATIONAL
4) Should we add other web component categories?

**Comment by rcavaliere** [comment]
@Piiit thanks for the details. No, let's just consider station that are sactive = TRUE for simplicity reasons

**Comment by Piiit** [comment]
OK, but what is then in_use vs. not_in_use?

1) total => sactive.eq.true or sactive.eq.false
2) not_operational => sactive.eq.false
3) operational_in_use => sactive.eq.true and ?
3) operational_not_in_use => sactive.eq.true and ?

**Comment by Piiit** [comment]
Aaa, now I get it... I will use just stations that are sactive = TRUE in general for all categories.

**Comment by rcavaliere** [comment]
@Piiit exact, this is the basis condition for all categories

**Comment by Piiit** [comment]
@rcavaliere My calculations are as follows now (always only for sactive = TRUE):
- not_operational = 100 - OCCUPIED - AVAILABLE - ACTIVE
- operational_in_use = OCCUPIED
- operational_not_in_use = AVAILABLE + ACTIVE

Could it be that we do not use a single station at the moment, as OCCUPIED is zero?

**Comment by Piiit** [comment]
Does ACTIVE mean used?

**Comment by rcavaliere** [comment]
Why do you consider ACTIVE here? The only available status should be AVAILABLE, OCCUPIED, RESERVED, UNAVAILABLE and FAULT

**Comment by rcavaliere** [comment]
Considering this, the association should be:
operational = AVAILABLE
operational_in_use = OCCUPIED
operational_not_in_use = UNAVAILABLE + FAULT
RESERVED should at present not be used

**Comment by Piiit** [comment]
At the moment we have only ACTIVE, AVAILABLE, FAULT, TEMPORARYUNAVAILABLE, UNKNOWN when sactive = TRUE

So we do not have a single OCCUPIED at the moment. RESERVED does not exist in our data

**Comment by Piiit** [comment]
Each station has only a single state here, so I cannot overlap your "operational" with the other two

**Comment by rcavaliere** [comment]
Where are these status stored in the DB?

**Comment by Piiit** [comment]
in metadata for the stations

**Comment by rcavaliere** [comment]
The status ACTIVE should just be related to stations that are under stationtype = 'EChargingStation'. The ohter status are related to stations that stationtype = 'EChargingPlug'. Is it like this?

**Comment by Piiit** [comment]
No, all states are related to EChargingStation

**Comment by Piiit** [comment]
I tried 
```sql
select count(*), m."json"->>'state' from station s 
join metadata m on s.meta_data_id = m.id 
where s.stationtype = 'EChargingStation'
and s.active = true
group by m."json"->>'state'
```

which gives 

```
count|?column?            |
-----|--------------------|
  366|ACTIVE              |
   46|AVAILABLE           |
    8|FAULT               |
   45|TEMPORARYUNAVAILABLE|
   45|UNKNOWN             |
```

**Comment by rcavaliere** [comment]
@Piiit ok, I have finally found in the specification (sorry, but I was replying this during other calls...). I put also there so that you can see it, it is the specification we agreed with the e-mobility data providers years ago. All the thing here is described at page 3. What should be is that the EChargingStations should have a metadata called "state" which can be "ACTIVE" or "TEMPORARYUNAVAILABLE". The EChargingPoint associated have also a metadata "state" which can be "AVAILABLE", "OCCUPIED", "RESERVED", "UNAVAILABLE", and "FAULTED".

Considering what we want to visualize, the rules should be these:

- IN OPERATION = EChargingStation ACTIVE and at least one EChargingPoint associated AVAILABLE
- IN USE = EChargingStation ACTIVE and all EChargingPoints associated OCCUPIED
- NOT IN OPERATION = ECharging TEMPORARYUNAVAILABLE (should have per consistency reason EChargingPlug UNAVAILABLE and FAULTED)

If EChargingStation have, as you say, a status which should be associated to a EChargingPlug this is a data quality issue we should report to the data provider. However, for our statistics we can consider the following adapted rules:

 - IN OPERATION = EChargingStation (ACTIVE or AVAILABLE) and at least one EChargingPoint associated AVAILABLE
- IN USE = EChargingStation (ACTIVE or AVAILABLE) and all EChargingPoints associated OCCUPIED
- NOT IN OPERATION = ECharging (TEMPORARYUNAVAILABLE or FAULT) (should have per consistency reason EChargingPlug UNAVAILABLE and [FAULTED)
[180201_SpecificheAPI_v1.1.pdf](https://github.com/noi-techpark/webcomp-mobility-echarging-dashboard/files/5920583/180201_SpecificheAPI_v1.1.pdf)

**Comment by Piiit** [comment]
@rcavaliere Done, please test again...

**Comment by rcavaliere** [comment]
Seems to be OK, wonderful. I share this with STA so that they can also check the statistics. The font is configurable, isn't it?

**Comment by rcavaliere** [comment]
@Piiit I got a feedback from STA. Very positive indeed!
They just ask if it possible to see the exact number in the tooltip or better in the centre of the circle when you go with the mouse over one of the colored parts of the plot (at present you see a tooltip with the %).
I also fixed some Italian translation: 
https://github.com/noi-techpark/webcomp-mobility-echarging-dashboard/pull/26
but I am not sure if the PR were successful merged, since I don't see the corrected translations implemented yet - maybe you can check this?

**Comment by rcavaliere** [comment]
@Piiit many thanks if you can provide me also here a feedback so to answer STA!

**Comment by Piiit** [comment]
@rcavaliere Yes, your PR was successfully merged, but the release on the store is not automatic yet. 

I released the new translations. They are online on testing and should be ready for production in a few minutes automatically.
https://webcomponents.opendatahub.testingmachine.eu/webcomponent/f594de36-0136-4c27-a0e6-570fa7014129 
v2.0.1

I can add the numbers as suggested by STA, but that will be next sprint... hope that is OK. I will create a new user story for that, since this one is growing :-)

**Comment by rcavaliere** [comment]
Fine with that. I am not sure however that the corrected translations have been correctly deployed yet... I see for example "Funzionamento momentaneamente delle prese"

**Comment by Piiit** [comment]
@rcavaliere It is not, because you committed to master and not development... See https://github.com/noi-techpark/webcomp-mobility-echarging-dashboard/network... please always commit to the development branch first... I will fix that when I merge the new user story.
