### ISSUE TITLE
Number of plugs or stations in the center of the circle, when hovering colored parts of the plot

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-mobility-echarging-dashboard#28]
exact number in the tooltip or better in the centre of the circle when you go with the mouse over one of the colored parts of the plot (at present you see a tooltip with the %).

**Comment by Piiit** [comment]
@rcavaliere FYI

**Comment by Piiit** [comment]
@rcavaliere Done, please see https://webcomponents.opendatahub.testingmachine.eu/webcomponent/f594de36-0136-4c27-a0e6-570fa7014129 

Looking forward to your feedback... when you are ready, let me know, so we put it into production

**Comment by Piiit** [comment]
I have also improved some parts of the code, reduced the size and merged several methods into one... so the distributed javascript will be smaller, hence faster loading :-)

**Comment by rcavaliere** [comment]
Very good, I think this improvement is good and in line with the request we got. You can put this improvement in production

**Comment by Piiit** [comment]
@rcavaliere Done, see https://webcomponents.opendatahub.bz.it/webcomponent/f594de36-0136-4c27-a0e6-570fa7014129
