### ISSUE TITLE
As an E-Mobility Web Component Data Consumer I would like to have a different sorting of the legend

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-echarging-dashboard#58]
STA Green Mobility asks to sort the legend from the type of charging type which is more used up to the less used. The type "700 bar small vehicles" should be renamed "H2-Station: 700 bar small vehicle" (it is not clear that it refers to the H2 charging stations).

![image001](https://user-images.githubusercontent.com/9825179/213640499-d1a8d699-baee-46f1-8698-b67529f1e59c.png)

**Comment by clezag** [comment]
I've modified the web component, @rcavaliere it's up on testing if you want to take a look

**Comment by rcavaliere** [comment]
@clezag very good! We can release on production

**Comment by clezag** [comment]
@rcavaliere released in production
