### ISSUE TITLE
As a consumer of this web comp, I want to have it integrated in the store with all features described

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-mobility-echarging-dashboard#8]
**Prerequisites**

- [x] Update the store webcomp-configtool, such that it supports null fields, that is fields that have only a key and not a value (prerequisite for the new "only-bolzano" feature)
- [x] Fix a bug that prevents the store API to show "required" and "label" fields
- [x] @rcavaliere will also update metadata inside [wcs-manifest.json](https://github.com/noi-techpark/webcomp-mobility-echarging-dashboard/blob/master/wcs-manifest.json) 

**Check and fix (email by @rcavaliere)**

- [x] si chiede di ingrandire leggermente le dimensioni del logo embedded (attualmente il logo Green Mobility)
> Not done, @Piiit will fix that --> DONE
- [x] oltre alla rappresentazione di tutti i dati gestiti dall'Open Data Hub, si vorrebbe avere una view aggiuntiva limitata alla Provincia di Bolzano. A tal proposito viene in aiuto la nostra nuova versione dell'API (API v2) che dovrebbe semplificare e velocizzare notevolmente queste query. L'end-point della nuova API è questo: http://ipchannels.integreen-life.bz.it/ninja/swagger-ui.html
> Done by Belka
- [x] per ciascuna di queste view, si vorrebbe evidenziare anche il nr. di stazioni pubbliche / private ad accesso pubblico / ....
> Done with percentages
- [x] a livello comunicativo deve essere chiaro se stiamo mostrando colonnine di ricarica o le singole prese. Forse si potrebbe mettere entrambe le statistiche (NB: coloumn in inglese è sbagliato, il termine giusto è "charging station"). --> Missing, fixed by @Piiit... 
     - [ ] will be finalized by @rcavaliere --> See [translations.js](https://github.com/noi-techpark/webcomp-mobility-echarging-dashboard/blob/master/src/translations.js)
- [x] In merito al punto API: eviterei di rifare tutto, quello che si potrebbe implementare nuovamente è la parte relativa alla dashboard.

**Comment by rcavaliere** [comment]
> oltre alla rappresentazione di tutti i dati gestiti dall'Open Data Hub, si vorrebbe avere una view aggiuntiva limitata alla Provincia di Bolzano

I have seen that with this filter we see just the data of the city of Bolzano, not of the Province of Bolzano. Can we adjust this, @Piiit ?

**Comment by rcavaliere** [comment]
>     * @rcavaliere will also update metadata inside [wcs-manifest.json](https://github.com/noi-techpark/webcomp-mobility-echarging-dashboard/blob/master/src/wcs-manifest.json)

the link is broken, I don't see the manifest file anymore...

**Comment by Piiit** [comment]
@rcavaliere Link fixed

**Comment by Piiit** [comment]
> I have seen that with this filter we see just the data of the **city of Bolzano**, not of the **Province of Bolzano**. Can we adjust this, @Piiit ?

@rcavaliere Done, it will be online with v1.5.0 in short time

**Comment by Piiit** [comment]
@rcavaliere This web component also supports only the main 3 languages now

**Comment by rcavaliere** [comment]
Thanks, done. I suggest to put everything in production. Please notify me when you have done this so that I can inform STA with all necessary information in order to integrate the webcomponents in the page https://www.greenmobility.bz.it/en/green-mobility/charging-stations/
